language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r dev-requirements.txt

script:
  - "PYTHONPATH=. py.test --cov=language_detector tests"

notifications:
  webhooks:
    urls:
      - http://requestb.in/11lkkui1
    on_success: always
    on_failure: never
    on_start: never


